// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countAuditLogsByUser = `-- name: CountAuditLogsByUser :one
SELECT COUNT(*) FROM audit_logs
WHERE user_id = $1
`

func (q *Queries) CountAuditLogsByUser(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    user_id,
    action,
    resource_type,
    resource_id,
    old_values,
    new_values,
    ip_address,
    user_agent,
    request_id,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, action, resource_type, resource_id, old_values, new_values, ip_address, user_agent, request_id, status, created_at
`

type CreateAuditLogParams struct {
	UserID       uuid.NullUUID         `json:"user_id"`
	Action       string                `json:"action"`
	ResourceType string                `json:"resource_type"`
	ResourceID   uuid.UUID             `json:"resource_id"`
	OldValues    pqtype.NullRawMessage `json:"old_values"`
	NewValues    pqtype.NullRawMessage `json:"new_values"`
	IpAddress    pqtype.Inet           `json:"ip_address"`
	UserAgent    sql.NullString        `json:"user_agent"`
	RequestID    sql.NullString        `json:"request_id"`
	Status       string                `json:"status"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.Status,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.OldValues,
		&i.NewValues,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogsByRequestID = `-- name: GetAuditLogsByRequestID :one
SELECT id, user_id, action, resource_type, resource_id, old_values, new_values, ip_address, user_agent, request_id, status, created_at FROM audit_logs
WHERE request_id = $1
LIMIT 1
`

func (q *Queries) GetAuditLogsByRequestID(ctx context.Context, requestID sql.NullString) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAuditLogsByRequestID, requestID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.OldValues,
		&i.NewValues,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogsByResource = `-- name: GetAuditLogsByResource :many
SELECT id, user_id, action, resource_type, resource_id, old_values, new_values, ip_address, user_agent, request_id, status, created_at FROM audit_logs
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetAuditLogsByResourceParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) GetAuditLogsByResource(ctx context.Context, arg GetAuditLogsByResourceParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByResource,
		arg.ResourceType,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByUserID = `-- name: GetAuditLogsByUserID :many
SELECT id, user_id, action, resource_type, resource_id, old_values, new_values, ip_address, user_agent, request_id, status, created_at FROM audit_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuditLogsByUserIDParams struct {
	UserID uuid.NullUUID `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) GetAuditLogsByUserID(ctx context.Context, arg GetAuditLogsByUserIDParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
