// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bills.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countUserBills = `-- name: CountUserBills :one
SELECT COUNT(*) FROM bills
WHERE user_id = $1
`

func (q *Queries) CountUserBills(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserBills, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBill = `-- name: CreateBill :one
INSERT INTO bills (
    user_id,
    type,
    status,
    barcode,
    amount_cents,
    fee_cents,
    final_amount_cents,
    recipient_name,
    due_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, type, status, barcode, amount_cents, fee_cents, final_amount_cents, recipient_name, due_date, payment_date, created_at
`

type CreateBillParams struct {
	UserID           uuid.UUID     `json:"user_id"`
	Type             string        `json:"type"`
	Status           string        `json:"status"`
	Barcode          string        `json:"barcode"`
	AmountCents      int64         `json:"amount_cents"`
	FeeCents         sql.NullInt64 `json:"fee_cents"`
	FinalAmountCents int64         `json:"final_amount_cents"`
	RecipientName    string        `json:"recipient_name"`
	DueDate          time.Time     `json:"due_date"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, createBill,
		arg.UserID,
		arg.Type,
		arg.Status,
		arg.Barcode,
		arg.AmountCents,
		arg.FeeCents,
		arg.FinalAmountCents,
		arg.RecipientName,
		arg.DueDate,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Barcode,
		&i.AmountCents,
		&i.FeeCents,
		&i.FinalAmountCents,
		&i.RecipientName,
		&i.DueDate,
		&i.PaymentDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBill = `-- name: DeleteBill :exec
UPDATE bills
SET status = 'cancelled'
WHERE id = $1
`

func (q *Queries) DeleteBill(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBill, id)
	return err
}

const getBillByBarcode = `-- name: GetBillByBarcode :one
SELECT id, user_id, type, status, barcode, amount_cents, fee_cents, final_amount_cents, recipient_name, due_date, payment_date, created_at FROM bills
WHERE barcode = $1
LIMIT 1
`

func (q *Queries) GetBillByBarcode(ctx context.Context, barcode string) (Bill, error) {
	row := q.db.QueryRowContext(ctx, getBillByBarcode, barcode)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Barcode,
		&i.AmountCents,
		&i.FeeCents,
		&i.FinalAmountCents,
		&i.RecipientName,
		&i.DueDate,
		&i.PaymentDate,
		&i.CreatedAt,
	)
	return i, err
}

const getBillByID = `-- name: GetBillByID :one
SELECT id, user_id, type, status, barcode, amount_cents, fee_cents, final_amount_cents, recipient_name, due_date, payment_date, created_at FROM bills
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBillByID(ctx context.Context, id uuid.UUID) (Bill, error) {
	row := q.db.QueryRowContext(ctx, getBillByID, id)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Barcode,
		&i.AmountCents,
		&i.FeeCents,
		&i.FinalAmountCents,
		&i.RecipientName,
		&i.DueDate,
		&i.PaymentDate,
		&i.CreatedAt,
	)
	return i, err
}

const getBillForUpdate = `-- name: GetBillForUpdate :one
SELECT id, user_id, type, status, barcode, amount_cents, fee_cents, final_amount_cents, recipient_name, due_date, payment_date, created_at FROM bills
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetBillForUpdate(ctx context.Context, id uuid.UUID) (Bill, error) {
	row := q.db.QueryRowContext(ctx, getBillForUpdate, id)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Barcode,
		&i.AmountCents,
		&i.FeeCents,
		&i.FinalAmountCents,
		&i.RecipientName,
		&i.DueDate,
		&i.PaymentDate,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBillsStats = `-- name: GetUserBillsStats :one
SELECT
    COUNT(*) as total_bills,
    COUNT(*) FILTER (WHERE status = 'pending') as pending_bills,
    COUNT(*) FILTER (WHERE status = 'paid') as paid_bills,
    COALESCE(SUM(final_amount_cents) FILTER (WHERE status = 'pending'), 0)::bigint as pending_amount_cents,
    COALESCE(SUM(final_amount_cents) FILTER (WHERE status = 'paid'), 0)::bigint as paid_amount_cents
FROM bills
WHERE user_id = $1
`

type GetUserBillsStatsRow struct {
	TotalBills         int64 `json:"total_bills"`
	PendingBills       int64 `json:"pending_bills"`
	PaidBills          int64 `json:"paid_bills"`
	PendingAmountCents int64 `json:"pending_amount_cents"`
	PaidAmountCents    int64 `json:"paid_amount_cents"`
}

func (q *Queries) GetUserBillsStats(ctx context.Context, userID uuid.UUID) (GetUserBillsStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBillsStats, userID)
	var i GetUserBillsStatsRow
	err := row.Scan(
		&i.TotalBills,
		&i.PendingBills,
		&i.PaidBills,
		&i.PendingAmountCents,
		&i.PaidAmountCents,
	)
	return i, err
}

const listOverdueBills = `-- name: ListOverdueBills :many
SELECT id, user_id, type, status, barcode, amount_cents, fee_cents, final_amount_cents, recipient_name, due_date, payment_date, created_at FROM bills
WHERE status = 'pending'
  AND due_date < CURRENT_DATE
ORDER BY due_date ASC
LIMIT $1 OFFSET $2
`

type ListOverdueBillsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOverdueBills(ctx context.Context, arg ListOverdueBillsParams) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, listOverdueBills, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bill{}
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Barcode,
			&i.AmountCents,
			&i.FeeCents,
			&i.FinalAmountCents,
			&i.RecipientName,
			&i.DueDate,
			&i.PaymentDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBills = `-- name: ListUserBills :many
SELECT id, user_id, type, status, barcode, amount_cents, fee_cents, final_amount_cents, recipient_name, due_date, payment_date, created_at FROM bills
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserBillsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserBills(ctx context.Context, arg ListUserBillsParams) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, listUserBills, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bill{}
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Barcode,
			&i.AmountCents,
			&i.FeeCents,
			&i.FinalAmountCents,
			&i.RecipientName,
			&i.DueDate,
			&i.PaymentDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBillsByStatus = `-- name: ListUserBillsByStatus :many
SELECT id, user_id, type, status, barcode, amount_cents, fee_cents, final_amount_cents, recipient_name, due_date, payment_date, created_at FROM bills
WHERE user_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUserBillsByStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserBillsByStatus(ctx context.Context, arg ListUserBillsByStatusParams) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, listUserBillsByStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bill{}
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Barcode,
			&i.AmountCents,
			&i.FeeCents,
			&i.FinalAmountCents,
			&i.RecipientName,
			&i.DueDate,
			&i.PaymentDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBillAsPaid = `-- name: MarkBillAsPaid :one
UPDATE bills
SET
    status = 'paid',
    payment_date = NOW()
WHERE id = $1
RETURNING id, user_id, type, status, barcode, amount_cents, fee_cents, final_amount_cents, recipient_name, due_date, payment_date, created_at
`

func (q *Queries) MarkBillAsPaid(ctx context.Context, id uuid.UUID) (Bill, error) {
	row := q.db.QueryRowContext(ctx, markBillAsPaid, id)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Barcode,
		&i.AmountCents,
		&i.FeeCents,
		&i.FinalAmountCents,
		&i.RecipientName,
		&i.DueDate,
		&i.PaymentDate,
		&i.CreatedAt,
	)
	return i, err
}

const updateBillStatus = `-- name: UpdateBillStatus :one
UPDATE bills
SET status = $2
WHERE id = $1
RETURNING id, user_id, type, status, barcode, amount_cents, fee_cents, final_amount_cents, recipient_name, due_date, payment_date, created_at
`

type UpdateBillStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateBillStatus(ctx context.Context, arg UpdateBillStatusParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, updateBillStatus, arg.ID, arg.Status)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Barcode,
		&i.AmountCents,
		&i.FeeCents,
		&i.FinalAmountCents,
		&i.RecipientName,
		&i.DueDate,
		&i.PaymentDate,
		&i.CreatedAt,
	)
	return i, err
}
