// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUserActiveCards = `-- name: CountUserActiveCards :one
SELECT COUNT(*) FROM cards
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CountUserActiveCards(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserActiveCards, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserCards = `-- name: CountUserCards :one
SELECT COUNT(*) FROM cards
WHERE user_id = $1
`

func (q *Queries) CountUserCards(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserCards, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCard = `-- name: CreateCard :one

INSERT INTO cards (
    user_id,
    type,
    brand,
    status,
    card_number_encrypted,
    cvv_encrypted,
    pin_hash,
    last_four_digits,
    holder_name,
    expiry_month,
    expiry_year,
    daily_limit_cents,
    monthly_limit_cents,
    current_daily_spent_cents,
    current_monthly_spent_cents,
    is_contactless,
    is_international,
    block_international,
    block_online,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
RETURNING id, user_id, type, brand, status, card_number_encrypted, cvv_encrypted, pin_hash, last_four_digits, holder_name, expiry_month, expiry_year, daily_limit_cents, monthly_limit_cents, current_daily_spent_cents, current_monthly_spent_cents, is_contactless, is_international, block_international, block_online, created_at, updated_at, expires_at, blocked_at
`

type CreateCardParams struct {
	UserID                   uuid.UUID      `json:"user_id"`
	Type                     string         `json:"type"`
	Brand                    string         `json:"brand"`
	Status                   string         `json:"status"`
	CardNumberEncrypted      []byte         `json:"card_number_encrypted"`
	CvvEncrypted             []byte         `json:"cvv_encrypted"`
	PinHash                  sql.NullString `json:"pin_hash"`
	LastFourDigits           string         `json:"last_four_digits"`
	HolderName               string         `json:"holder_name"`
	ExpiryMonth              int16          `json:"expiry_month"`
	ExpiryYear               int16          `json:"expiry_year"`
	DailyLimitCents          sql.NullInt64  `json:"daily_limit_cents"`
	MonthlyLimitCents        sql.NullInt64  `json:"monthly_limit_cents"`
	CurrentDailySpentCents   sql.NullInt64  `json:"current_daily_spent_cents"`
	CurrentMonthlySpentCents sql.NullInt64  `json:"current_monthly_spent_cents"`
	IsContactless            sql.NullBool   `json:"is_contactless"`
	IsInternational          sql.NullBool   `json:"is_international"`
	BlockInternational       sql.NullBool   `json:"block_international"`
	BlockOnline              sql.NullBool   `json:"block_online"`
	ExpiresAt                sql.NullTime   `json:"expires_at"`
}

// ========================================
// CARDS QUERIES
// ========================================
func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.UserID,
		arg.Type,
		arg.Brand,
		arg.Status,
		arg.CardNumberEncrypted,
		arg.CvvEncrypted,
		arg.PinHash,
		arg.LastFourDigits,
		arg.HolderName,
		arg.ExpiryMonth,
		arg.ExpiryYear,
		arg.DailyLimitCents,
		arg.MonthlyLimitCents,
		arg.CurrentDailySpentCents,
		arg.CurrentMonthlySpentCents,
		arg.IsContactless,
		arg.IsInternational,
		arg.BlockInternational,
		arg.BlockOnline,
		arg.ExpiresAt,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Brand,
		&i.Status,
		&i.CardNumberEncrypted,
		&i.CvvEncrypted,
		&i.PinHash,
		&i.LastFourDigits,
		&i.HolderName,
		&i.ExpiryMonth,
		&i.ExpiryYear,
		&i.DailyLimitCents,
		&i.MonthlyLimitCents,
		&i.CurrentDailySpentCents,
		&i.CurrentMonthlySpentCents,
		&i.IsContactless,
		&i.IsInternational,
		&i.BlockInternational,
		&i.BlockOnline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.BlockedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
UPDATE cards
SET
    status = 'cancelled',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCard, id)
	return err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, user_id, type, brand, status, card_number_encrypted, cvv_encrypted, pin_hash, last_four_digits, holder_name, expiry_month, expiry_year, daily_limit_cents, monthly_limit_cents, current_daily_spent_cents, current_monthly_spent_cents, is_contactless, is_international, block_international, block_online, created_at, updated_at, expires_at, blocked_at FROM cards
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCardByID(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Brand,
		&i.Status,
		&i.CardNumberEncrypted,
		&i.CvvEncrypted,
		&i.PinHash,
		&i.LastFourDigits,
		&i.HolderName,
		&i.ExpiryMonth,
		&i.ExpiryYear,
		&i.DailyLimitCents,
		&i.MonthlyLimitCents,
		&i.CurrentDailySpentCents,
		&i.CurrentMonthlySpentCents,
		&i.IsContactless,
		&i.IsInternational,
		&i.BlockInternational,
		&i.BlockOnline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.BlockedAt,
	)
	return i, err
}

const getCardForUpdate = `-- name: GetCardForUpdate :one
SELECT id, user_id, type, brand, status, card_number_encrypted, cvv_encrypted, pin_hash, last_four_digits, holder_name, expiry_month, expiry_year, daily_limit_cents, monthly_limit_cents, current_daily_spent_cents, current_monthly_spent_cents, is_contactless, is_international, block_international, block_online, created_at, updated_at, expires_at, blocked_at FROM cards
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCardForUpdate(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardForUpdate, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Brand,
		&i.Status,
		&i.CardNumberEncrypted,
		&i.CvvEncrypted,
		&i.PinHash,
		&i.LastFourDigits,
		&i.HolderName,
		&i.ExpiryMonth,
		&i.ExpiryYear,
		&i.DailyLimitCents,
		&i.MonthlyLimitCents,
		&i.CurrentDailySpentCents,
		&i.CurrentMonthlySpentCents,
		&i.IsContactless,
		&i.IsInternational,
		&i.BlockInternational,
		&i.BlockOnline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.BlockedAt,
	)
	return i, err
}

const getUserCardsByStatus = `-- name: GetUserCardsByStatus :many
SELECT id, user_id, type, brand, status, card_number_encrypted, cvv_encrypted, pin_hash, last_four_digits, holder_name, expiry_month, expiry_year, daily_limit_cents, monthly_limit_cents, current_daily_spent_cents, current_monthly_spent_cents, is_contactless, is_international, block_international, block_online, created_at, updated_at, expires_at, blocked_at FROM cards
WHERE user_id = $1 AND status = $2
ORDER BY created_at DESC
`

type GetUserCardsByStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) GetUserCardsByStatus(ctx context.Context, arg GetUserCardsByStatusParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getUserCardsByStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Brand,
			&i.Status,
			&i.CardNumberEncrypted,
			&i.CvvEncrypted,
			&i.PinHash,
			&i.LastFourDigits,
			&i.HolderName,
			&i.ExpiryMonth,
			&i.ExpiryYear,
			&i.DailyLimitCents,
			&i.MonthlyLimitCents,
			&i.CurrentDailySpentCents,
			&i.CurrentMonthlySpentCents,
			&i.IsContactless,
			&i.IsInternational,
			&i.BlockInternational,
			&i.BlockOnline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.BlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUserCards = `-- name: ListActiveUserCards :many
SELECT id, user_id, type, brand, status, card_number_encrypted, cvv_encrypted, pin_hash, last_four_digits, holder_name, expiry_month, expiry_year, daily_limit_cents, monthly_limit_cents, current_daily_spent_cents, current_monthly_spent_cents, is_contactless, is_international, block_international, block_online, created_at, updated_at, expires_at, blocked_at FROM cards
WHERE user_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveUserCards(ctx context.Context, userID uuid.UUID) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUserCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Brand,
			&i.Status,
			&i.CardNumberEncrypted,
			&i.CvvEncrypted,
			&i.PinHash,
			&i.LastFourDigits,
			&i.HolderName,
			&i.ExpiryMonth,
			&i.ExpiryYear,
			&i.DailyLimitCents,
			&i.MonthlyLimitCents,
			&i.CurrentDailySpentCents,
			&i.CurrentMonthlySpentCents,
			&i.IsContactless,
			&i.IsInternational,
			&i.BlockInternational,
			&i.BlockOnline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.BlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCards = `-- name: ListUserCards :many
SELECT id, user_id, type, brand, status, card_number_encrypted, cvv_encrypted, pin_hash, last_four_digits, holder_name, expiry_month, expiry_year, daily_limit_cents, monthly_limit_cents, current_daily_spent_cents, current_monthly_spent_cents, is_contactless, is_international, block_international, block_online, created_at, updated_at, expires_at, blocked_at FROM cards
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserCards(ctx context.Context, userID uuid.UUID) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listUserCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Brand,
			&i.Status,
			&i.CardNumberEncrypted,
			&i.CvvEncrypted,
			&i.PinHash,
			&i.LastFourDigits,
			&i.HolderName,
			&i.ExpiryMonth,
			&i.ExpiryYear,
			&i.DailyLimitCents,
			&i.MonthlyLimitCents,
			&i.CurrentDailySpentCents,
			&i.CurrentMonthlySpentCents,
			&i.IsContactless,
			&i.IsInternational,
			&i.BlockInternational,
			&i.BlockOnline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.BlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAllDailySpent = `-- name: ResetAllDailySpent :exec
UPDATE cards
SET
    current_daily_spent_cents = 0,
    updated_at = NOW()
WHERE status = 'active'
`

func (q *Queries) ResetAllDailySpent(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAllDailySpent)
	return err
}

const resetAllMonthlySpent = `-- name: ResetAllMonthlySpent :exec
UPDATE cards
SET
    current_monthly_spent_cents = 0,
    updated_at = NOW()
WHERE status = 'active'
`

func (q *Queries) ResetAllMonthlySpent(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAllMonthlySpent)
	return err
}

const resetDailySpent = `-- name: ResetDailySpent :exec
UPDATE cards
SET
    current_daily_spent_cents = 0,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetDailySpent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetDailySpent, id)
	return err
}

const resetMonthlySpent = `-- name: ResetMonthlySpent :exec
UPDATE cards
SET
    current_monthly_spent_cents = 0,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetMonthlySpent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetMonthlySpent, id)
	return err
}

const updateCardLimits = `-- name: UpdateCardLimits :exec
UPDATE cards
SET
    daily_limit_cents = $2,
    monthly_limit_cents = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCardLimitsParams struct {
	ID                uuid.UUID     `json:"id"`
	DailyLimitCents   sql.NullInt64 `json:"daily_limit_cents"`
	MonthlyLimitCents sql.NullInt64 `json:"monthly_limit_cents"`
}

func (q *Queries) UpdateCardLimits(ctx context.Context, arg UpdateCardLimitsParams) error {
	_, err := q.db.ExecContext(ctx, updateCardLimits, arg.ID, arg.DailyLimitCents, arg.MonthlyLimitCents)
	return err
}

const updateCardPIN = `-- name: UpdateCardPIN :exec
UPDATE cards
SET
    pin_hash = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCardPINParams struct {
	ID      uuid.UUID      `json:"id"`
	PinHash sql.NullString `json:"pin_hash"`
}

func (q *Queries) UpdateCardPIN(ctx context.Context, arg UpdateCardPINParams) error {
	_, err := q.db.ExecContext(ctx, updateCardPIN, arg.ID, arg.PinHash)
	return err
}

const updateCardSecuritySettings = `-- name: UpdateCardSecuritySettings :exec
UPDATE cards
SET
    is_contactless = $2,
    is_international = $3,
    block_international = $4,
    block_online = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCardSecuritySettingsParams struct {
	ID                 uuid.UUID    `json:"id"`
	IsContactless      sql.NullBool `json:"is_contactless"`
	IsInternational    sql.NullBool `json:"is_international"`
	BlockInternational sql.NullBool `json:"block_international"`
	BlockOnline        sql.NullBool `json:"block_online"`
}

func (q *Queries) UpdateCardSecuritySettings(ctx context.Context, arg UpdateCardSecuritySettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateCardSecuritySettings,
		arg.ID,
		arg.IsContactless,
		arg.IsInternational,
		arg.BlockInternational,
		arg.BlockOnline,
	)
	return err
}

const updateCardSpentAmounts = `-- name: UpdateCardSpentAmounts :exec
UPDATE cards
SET
    current_daily_spent_cents = $2,
    current_monthly_spent_cents = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCardSpentAmountsParams struct {
	ID                       uuid.UUID     `json:"id"`
	CurrentDailySpentCents   sql.NullInt64 `json:"current_daily_spent_cents"`
	CurrentMonthlySpentCents sql.NullInt64 `json:"current_monthly_spent_cents"`
}

func (q *Queries) UpdateCardSpentAmounts(ctx context.Context, arg UpdateCardSpentAmountsParams) error {
	_, err := q.db.ExecContext(ctx, updateCardSpentAmounts, arg.ID, arg.CurrentDailySpentCents, arg.CurrentMonthlySpentCents)
	return err
}

const updateCardStatus = `-- name: UpdateCardStatus :exec
UPDATE cards
SET
    status = $2,
    blocked_at = CASE
        WHEN $2 = 'blocked' THEN NOW()
        WHEN $2 = 'active' THEN NULL
        ELSE blocked_at
    END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCardStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCardStatus(ctx context.Context, arg UpdateCardStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCardStatus, arg.ID, arg.Status)
	return err
}
