// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID           uuid.UUID             `json:"id"`
	UserID       uuid.NullUUID         `json:"user_id"`
	Action       string                `json:"action"`
	ResourceType string                `json:"resource_type"`
	ResourceID   uuid.UUID             `json:"resource_id"`
	OldValues    pqtype.NullRawMessage `json:"old_values"`
	NewValues    pqtype.NullRawMessage `json:"new_values"`
	IpAddress    pqtype.Inet           `json:"ip_address"`
	UserAgent    sql.NullString        `json:"user_agent"`
	RequestID    sql.NullString        `json:"request_id"`
	Status       string                `json:"status"`
	CreatedAt    time.Time             `json:"created_at"`
}

type Bill struct {
	ID               uuid.UUID     `json:"id"`
	UserID           uuid.UUID     `json:"user_id"`
	Type             string        `json:"type"`
	Status           string        `json:"status"`
	Barcode          string        `json:"barcode"`
	AmountCents      int64         `json:"amount_cents"`
	FeeCents         sql.NullInt64 `json:"fee_cents"`
	FinalAmountCents int64         `json:"final_amount_cents"`
	RecipientName    string        `json:"recipient_name"`
	DueDate          time.Time     `json:"due_date"`
	PaymentDate      sql.NullTime  `json:"payment_date"`
	CreatedAt        sql.NullTime  `json:"created_at"`
}

type Budget struct {
	ID                uuid.UUID     `json:"id"`
	UserID            uuid.UUID     `json:"user_id"`
	Category          string        `json:"category"`
	Period            string        `json:"period"`
	LimitCents        int64         `json:"limit_cents"`
	CurrentSpentCents sql.NullInt64 `json:"current_spent_cents"`
	AlertThreshold    sql.NullInt16 `json:"alert_threshold"`
	AlertsEnabled     sql.NullBool  `json:"alerts_enabled"`
	StartDate         time.Time     `json:"start_date"`
	EndDate           time.Time     `json:"end_date"`
	CreatedAt         sql.NullTime  `json:"created_at"`
}

type Card struct {
	ID                       uuid.UUID      `json:"id"`
	UserID                   uuid.UUID      `json:"user_id"`
	Type                     string         `json:"type"`
	Brand                    string         `json:"brand"`
	Status                   string         `json:"status"`
	CardNumberEncrypted      []byte         `json:"card_number_encrypted"`
	CvvEncrypted             []byte         `json:"cvv_encrypted"`
	PinHash                  sql.NullString `json:"pin_hash"`
	LastFourDigits           string         `json:"last_four_digits"`
	HolderName               string         `json:"holder_name"`
	ExpiryMonth              int16          `json:"expiry_month"`
	ExpiryYear               int16          `json:"expiry_year"`
	DailyLimitCents          sql.NullInt64  `json:"daily_limit_cents"`
	MonthlyLimitCents        sql.NullInt64  `json:"monthly_limit_cents"`
	CurrentDailySpentCents   sql.NullInt64  `json:"current_daily_spent_cents"`
	CurrentMonthlySpentCents sql.NullInt64  `json:"current_monthly_spent_cents"`
	IsContactless            sql.NullBool   `json:"is_contactless"`
	IsInternational          sql.NullBool   `json:"is_international"`
	BlockInternational       sql.NullBool   `json:"block_international"`
	BlockOnline              sql.NullBool   `json:"block_online"`
	CreatedAt                sql.NullTime   `json:"created_at"`
	UpdatedAt                sql.NullTime   `json:"updated_at"`
	ExpiresAt                sql.NullTime   `json:"expires_at"`
	BlockedAt                sql.NullTime   `json:"blocked_at"`
}

type CardTransaction struct {
	ID               uuid.UUID      `json:"id"`
	CardID           uuid.UUID      `json:"card_id"`
	UserID           uuid.UUID      `json:"user_id"`
	AmountCents      int64          `json:"amount_cents"`
	MerchantName     string         `json:"merchant_name"`
	MerchantCategory sql.NullString `json:"merchant_category"`
	Status           string         `json:"status"`
	IsInternational  sql.NullBool   `json:"is_international"`
	TransactionDate  time.Time      `json:"transaction_date"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type SupportTicket struct {
	ID           uuid.UUID    `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	TicketNumber string       `json:"ticket_number"`
	Category     string       `json:"category"`
	Priority     string       `json:"priority"`
	Status       string       `json:"status"`
	Subject      string       `json:"subject"`
	Description  string       `json:"description"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type TicketMessage struct {
	ID        uuid.UUID    `json:"id"`
	TicketID  uuid.UUID    `json:"ticket_id"`
	UserID    uuid.UUID    `json:"user_id"`
	Message   string       `json:"message"`
	IsStaff   sql.NullBool `json:"is_staff"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Transfer struct {
	ID                   uuid.UUID      `json:"id"`
	UserID               uuid.UUID      `json:"user_id"`
	Type                 string         `json:"type"`
	Status               string         `json:"status"`
	AmountCents          int64          `json:"amount_cents"`
	FeeCents             sql.NullInt64  `json:"fee_cents"`
	Currency             sql.NullString `json:"currency"`
	PixKey               sql.NullString `json:"pix_key"`
	PixKeyType           sql.NullString `json:"pix_key_type"`
	RecipientName        sql.NullString `json:"recipient_name"`
	RecipientDocument    sql.NullString `json:"recipient_document"`
	RecipientBank        sql.NullString `json:"recipient_bank"`
	RecipientBranch      sql.NullString `json:"recipient_branch"`
	RecipientAccount     sql.NullString `json:"recipient_account"`
	RecipientAccountType sql.NullString `json:"recipient_account_type"`
	RecipientUserID      uuid.NullUUID  `json:"recipient_user_id"`
	ScheduledFor         sql.NullTime   `json:"scheduled_for"`
	CompletedAt          sql.NullTime   `json:"completed_at"`
	FailureReason        sql.NullString `json:"failure_reason"`
	AuthenticationCode   sql.NullString `json:"authentication_code"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID                        uuid.UUID      `json:"id"`
	KratosIdentityID          string         `json:"kratos_identity_id"`
	Email                     string         `json:"email"`
	FullName                  sql.NullString `json:"full_name"`
	Cpf                       sql.NullString `json:"cpf"`
	BalanceCents              sql.NullInt64  `json:"balance_cents"`
	DailyTransferLimitCents   sql.NullInt64  `json:"daily_transfer_limit_cents"`
	MonthlyTransferLimitCents sql.NullInt64  `json:"monthly_transfer_limit_cents"`
	Status                    sql.NullString `json:"status"`
	KycStatus                 sql.NullString `json:"kyc_status"`
	CreatedAt                 sql.NullTime   `json:"created_at"`
	UpdatedAt                 sql.NullTime   `json:"updated_at"`
}
