// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CancelTransfer(ctx context.Context, id uuid.UUID) (Transfer, error)
	CountAllTickets(ctx context.Context) (int64, error)
	CountAuditLogsByUser(ctx context.Context, userID uuid.NullUUID) (int64, error)
	CountCardTransactions(ctx context.Context, cardID uuid.UUID) (int64, error)
	CountTicketMessages(ctx context.Context, ticketID uuid.UUID) (int64, error)
	CountTicketsByStatus(ctx context.Context, status string) (int64, error)
	CountUserActiveCards(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserBills(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserBudgets(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserCards(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserTickets(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserTicketsByStatus(ctx context.Context, arg CountUserTicketsByStatusParams) (int64, error)
	CountUserTransfers(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	// ========================================
	// CARDS QUERIES
	// ========================================
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	CreateCardTransaction(ctx context.Context, arg CreateCardTransactionParams) (CardTransaction, error)
	// Support Tickets Queries
	CreateTicket(ctx context.Context, arg CreateTicketParams) (SupportTicket, error)
	// Ticket Messages Queries
	CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (TicketMessage, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBill(ctx context.Context, id uuid.UUID) error
	DeleteBudget(ctx context.Context, id uuid.UUID) error
	DeleteCard(ctx context.Context, id uuid.UUID) error
	DeleteTicket(ctx context.Context, id uuid.UUID) error
	DeleteTicketMessage(ctx context.Context, id uuid.UUID) error
	GetAuditLogsByRequestID(ctx context.Context, requestID sql.NullString) (AuditLog, error)
	GetAuditLogsByResource(ctx context.Context, arg GetAuditLogsByResourceParams) ([]AuditLog, error)
	GetAuditLogsByUserID(ctx context.Context, arg GetAuditLogsByUserIDParams) ([]AuditLog, error)
	GetBillByBarcode(ctx context.Context, barcode string) (Bill, error)
	GetBillByID(ctx context.Context, id uuid.UUID) (Bill, error)
	GetBillForUpdate(ctx context.Context, id uuid.UUID) (Bill, error)
	GetBudgetByCategoryAndPeriod(ctx context.Context, arg GetBudgetByCategoryAndPeriodParams) (Budget, error)
	GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error)
	GetBudgetForUpdate(ctx context.Context, id uuid.UUID) (Budget, error)
	GetBudgetsNearLimit(ctx context.Context, userID uuid.UUID) ([]Budget, error)
	GetCardByID(ctx context.Context, id uuid.UUID) (Card, error)
	GetCardForUpdate(ctx context.Context, id uuid.UUID) (Card, error)
	GetCardTransactionByID(ctx context.Context, id uuid.UUID) (CardTransaction, error)
	GetCardTransactionsByCategory(ctx context.Context, arg GetCardTransactionsByCategoryParams) ([]GetCardTransactionsByCategoryRow, error)
	GetCardTransactionsByDateRange(ctx context.Context, arg GetCardTransactionsByDateRangeParams) ([]CardTransaction, error)
	GetDailyTransferSum(ctx context.Context, userID uuid.UUID) (int64, error)
	GetLatestTicketMessage(ctx context.Context, ticketID uuid.UUID) (TicketMessage, error)
	GetMonthlyTransferSum(ctx context.Context, userID uuid.UUID) (int64, error)
	GetOverBudgets(ctx context.Context, userID uuid.UUID) ([]Budget, error)
	GetTicketByID(ctx context.Context, id uuid.UUID) (SupportTicket, error)
	GetTicketByNumber(ctx context.Context, ticketNumber string) (SupportTicket, error)
	GetTicketForUpdate(ctx context.Context, id uuid.UUID) (SupportTicket, error)
	GetTicketMessageByID(ctx context.Context, id uuid.UUID) (TicketMessage, error)
	GetTicketStats(ctx context.Context) (GetTicketStatsRow, error)
	GetTransferByID(ctx context.Context, id uuid.UUID) (Transfer, error)
	GetTransferForUpdate(ctx context.Context, id uuid.UUID) (Transfer, error)
	GetUserBillsStats(ctx context.Context, userID uuid.UUID) (GetUserBillsStatsRow, error)
	GetUserBudgetsAnalytics(ctx context.Context, userID uuid.UUID) (GetUserBudgetsAnalyticsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByKratosID(ctx context.Context, kratosIdentityID string) (User, error)
	GetUserCardsByStatus(ctx context.Context, arg GetUserCardsByStatusParams) ([]Card, error)
	GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error)
	IncrementBudgetSpent(ctx context.Context, arg IncrementBudgetSpentParams) (Budget, error)
	ListActiveUserCards(ctx context.Context, userID uuid.UUID) ([]Card, error)
	// Admin/Staff Queries
	ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]SupportTicket, error)
	ListCardTransactions(ctx context.Context, arg ListCardTransactionsParams) ([]CardTransaction, error)
	ListOverdueBills(ctx context.Context, arg ListOverdueBillsParams) ([]Bill, error)
	ListTicketMessages(ctx context.Context, arg ListTicketMessagesParams) ([]TicketMessage, error)
	ListTicketsByStatus(ctx context.Context, arg ListTicketsByStatusParams) ([]SupportTicket, error)
	ListUserBills(ctx context.Context, arg ListUserBillsParams) ([]Bill, error)
	ListUserBillsByStatus(ctx context.Context, arg ListUserBillsByStatusParams) ([]Bill, error)
	ListUserBudgets(ctx context.Context, arg ListUserBudgetsParams) ([]Budget, error)
	ListUserBudgetsByCategory(ctx context.Context, arg ListUserBudgetsByCategoryParams) ([]Budget, error)
	ListUserBudgetsByPeriod(ctx context.Context, arg ListUserBudgetsByPeriodParams) ([]Budget, error)
	ListUserCardTransactions(ctx context.Context, arg ListUserCardTransactionsParams) ([]CardTransaction, error)
	ListUserCards(ctx context.Context, userID uuid.UUID) ([]Card, error)
	ListUserTickets(ctx context.Context, arg ListUserTicketsParams) ([]SupportTicket, error)
	ListUserTicketsByStatus(ctx context.Context, arg ListUserTicketsByStatusParams) ([]SupportTicket, error)
	ListUserTransfers(ctx context.Context, arg ListUserTransfersParams) ([]Transfer, error)
	ListUserTransfersByStatus(ctx context.Context, arg ListUserTransfersByStatusParams) ([]Transfer, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkBillAsPaid(ctx context.Context, id uuid.UUID) (Bill, error)
	ResetAllDailySpent(ctx context.Context) error
	ResetAllMonthlySpent(ctx context.Context) error
	ResetBudgetSpent(ctx context.Context, userID uuid.UUID) error
	ResetDailySpent(ctx context.Context, id uuid.UUID) error
	ResetMonthlySpent(ctx context.Context, id uuid.UUID) error
	UpdateBillStatus(ctx context.Context, arg UpdateBillStatusParams) (Bill, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateBudgetSpent(ctx context.Context, arg UpdateBudgetSpentParams) (Budget, error)
	UpdateCardLimits(ctx context.Context, arg UpdateCardLimitsParams) error
	UpdateCardPIN(ctx context.Context, arg UpdateCardPINParams) error
	UpdateCardSecuritySettings(ctx context.Context, arg UpdateCardSecuritySettingsParams) error
	UpdateCardSpentAmounts(ctx context.Context, arg UpdateCardSpentAmountsParams) error
	UpdateCardStatus(ctx context.Context, arg UpdateCardStatusParams) error
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (SupportTicket, error)
	UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (SupportTicket, error)
	UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) (Transfer, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error
}

var _ Querier = (*Queries)(nil)
