// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cancelTransfer = `-- name: CancelTransfer :one
UPDATE transfers
SET
    status = 'cancelled',
    updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, type, status, amount_cents, fee_cents, currency, pix_key, pix_key_type, recipient_name, recipient_document, recipient_bank, recipient_branch, recipient_account, recipient_account_type, recipient_user_id, scheduled_for, completed_at, failure_reason, authentication_code, created_at, updated_at
`

func (q *Queries) CancelTransfer(ctx context.Context, id uuid.UUID) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, cancelTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.AmountCents,
		&i.FeeCents,
		&i.Currency,
		&i.PixKey,
		&i.PixKeyType,
		&i.RecipientName,
		&i.RecipientDocument,
		&i.RecipientBank,
		&i.RecipientBranch,
		&i.RecipientAccount,
		&i.RecipientAccountType,
		&i.RecipientUserID,
		&i.ScheduledFor,
		&i.CompletedAt,
		&i.FailureReason,
		&i.AuthenticationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUserTransfers = `-- name: CountUserTransfers :one
SELECT COUNT(*) FROM transfers
WHERE user_id = $1
`

func (q *Queries) CountUserTransfers(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserTransfers, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
    user_id,
    type,
    status,
    amount_cents,
    fee_cents,
    currency,
    pix_key,
    pix_key_type,
    recipient_name,
    recipient_document,
    recipient_bank,
    recipient_branch,
    recipient_account,
    recipient_account_type,
    recipient_user_id,
    scheduled_for,
    completed_at,
    failure_reason,
    authentication_code
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
RETURNING id, user_id, type, status, amount_cents, fee_cents, currency, pix_key, pix_key_type, recipient_name, recipient_document, recipient_bank, recipient_branch, recipient_account, recipient_account_type, recipient_user_id, scheduled_for, completed_at, failure_reason, authentication_code, created_at, updated_at
`

type CreateTransferParams struct {
	UserID               uuid.UUID      `json:"user_id"`
	Type                 string         `json:"type"`
	Status               string         `json:"status"`
	AmountCents          int64          `json:"amount_cents"`
	FeeCents             sql.NullInt64  `json:"fee_cents"`
	Currency             sql.NullString `json:"currency"`
	PixKey               sql.NullString `json:"pix_key"`
	PixKeyType           sql.NullString `json:"pix_key_type"`
	RecipientName        sql.NullString `json:"recipient_name"`
	RecipientDocument    sql.NullString `json:"recipient_document"`
	RecipientBank        sql.NullString `json:"recipient_bank"`
	RecipientBranch      sql.NullString `json:"recipient_branch"`
	RecipientAccount     sql.NullString `json:"recipient_account"`
	RecipientAccountType sql.NullString `json:"recipient_account_type"`
	RecipientUserID      uuid.NullUUID  `json:"recipient_user_id"`
	ScheduledFor         sql.NullTime   `json:"scheduled_for"`
	CompletedAt          sql.NullTime   `json:"completed_at"`
	FailureReason        sql.NullString `json:"failure_reason"`
	AuthenticationCode   sql.NullString `json:"authentication_code"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.UserID,
		arg.Type,
		arg.Status,
		arg.AmountCents,
		arg.FeeCents,
		arg.Currency,
		arg.PixKey,
		arg.PixKeyType,
		arg.RecipientName,
		arg.RecipientDocument,
		arg.RecipientBank,
		arg.RecipientBranch,
		arg.RecipientAccount,
		arg.RecipientAccountType,
		arg.RecipientUserID,
		arg.ScheduledFor,
		arg.CompletedAt,
		arg.FailureReason,
		arg.AuthenticationCode,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.AmountCents,
		&i.FeeCents,
		&i.Currency,
		&i.PixKey,
		&i.PixKeyType,
		&i.RecipientName,
		&i.RecipientDocument,
		&i.RecipientBank,
		&i.RecipientBranch,
		&i.RecipientAccount,
		&i.RecipientAccountType,
		&i.RecipientUserID,
		&i.ScheduledFor,
		&i.CompletedAt,
		&i.FailureReason,
		&i.AuthenticationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyTransferSum = `-- name: GetDailyTransferSum :one
SELECT COALESCE(SUM(amount_cents + fee_cents), 0)::bigint as total
FROM transfers
WHERE user_id = $1
  AND type IN ('pix', 'ted', 'p2p')
  AND status IN ('completed', 'processing', 'pending')
  AND created_at >= CURRENT_DATE
  AND created_at < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) GetDailyTransferSum(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDailyTransferSum, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getMonthlyTransferSum = `-- name: GetMonthlyTransferSum :one
SELECT COALESCE(SUM(amount_cents + fee_cents), 0)::bigint as total
FROM transfers
WHERE user_id = $1
  AND type IN ('pix', 'ted', 'p2p')
  AND status IN ('completed', 'processing', 'pending')
  AND created_at >= DATE_TRUNC('month', CURRENT_DATE)
  AND created_at < DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month'
`

func (q *Queries) GetMonthlyTransferSum(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyTransferSum, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getTransferByID = `-- name: GetTransferByID :one
SELECT id, user_id, type, status, amount_cents, fee_cents, currency, pix_key, pix_key_type, recipient_name, recipient_document, recipient_bank, recipient_branch, recipient_account, recipient_account_type, recipient_user_id, scheduled_for, completed_at, failure_reason, authentication_code, created_at, updated_at FROM transfers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransferByID(ctx context.Context, id uuid.UUID) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferByID, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.AmountCents,
		&i.FeeCents,
		&i.Currency,
		&i.PixKey,
		&i.PixKeyType,
		&i.RecipientName,
		&i.RecipientDocument,
		&i.RecipientBank,
		&i.RecipientBranch,
		&i.RecipientAccount,
		&i.RecipientAccountType,
		&i.RecipientUserID,
		&i.ScheduledFor,
		&i.CompletedAt,
		&i.FailureReason,
		&i.AuthenticationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransferForUpdate = `-- name: GetTransferForUpdate :one
SELECT id, user_id, type, status, amount_cents, fee_cents, currency, pix_key, pix_key_type, recipient_name, recipient_document, recipient_bank, recipient_branch, recipient_account, recipient_account_type, recipient_user_id, scheduled_for, completed_at, failure_reason, authentication_code, created_at, updated_at FROM transfers
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetTransferForUpdate(ctx context.Context, id uuid.UUID) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferForUpdate, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.AmountCents,
		&i.FeeCents,
		&i.Currency,
		&i.PixKey,
		&i.PixKeyType,
		&i.RecipientName,
		&i.RecipientDocument,
		&i.RecipientBank,
		&i.RecipientBranch,
		&i.RecipientAccount,
		&i.RecipientAccountType,
		&i.RecipientUserID,
		&i.ScheduledFor,
		&i.CompletedAt,
		&i.FailureReason,
		&i.AuthenticationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserTransfers = `-- name: ListUserTransfers :many
SELECT id, user_id, type, status, amount_cents, fee_cents, currency, pix_key, pix_key_type, recipient_name, recipient_document, recipient_bank, recipient_branch, recipient_account, recipient_account_type, recipient_user_id, scheduled_for, completed_at, failure_reason, authentication_code, created_at, updated_at FROM transfers
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserTransfersParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserTransfers(ctx context.Context, arg ListUserTransfersParams) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listUserTransfers, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.AmountCents,
			&i.FeeCents,
			&i.Currency,
			&i.PixKey,
			&i.PixKeyType,
			&i.RecipientName,
			&i.RecipientDocument,
			&i.RecipientBank,
			&i.RecipientBranch,
			&i.RecipientAccount,
			&i.RecipientAccountType,
			&i.RecipientUserID,
			&i.ScheduledFor,
			&i.CompletedAt,
			&i.FailureReason,
			&i.AuthenticationCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransferStatus = `-- name: UpdateTransferStatus :one
UPDATE transfers
SET
    status = $2,
    completed_at = CASE
        WHEN $2 = 'completed' THEN NOW()
        ELSE completed_at
    END,
    failure_reason = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, type, status, amount_cents, fee_cents, currency, pix_key, pix_key_type, recipient_name, recipient_document, recipient_bank, recipient_branch, recipient_account, recipient_account_type, recipient_user_id, scheduled_for, completed_at, failure_reason, authentication_code, created_at, updated_at
`

type UpdateTransferStatusParams struct {
	ID            uuid.UUID      `json:"id"`
	Status        string         `json:"status"`
	FailureReason sql.NullString `json:"failure_reason"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, updateTransferStatus, arg.ID, arg.Status, arg.FailureReason)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.AmountCents,
		&i.FeeCents,
		&i.Currency,
		&i.PixKey,
		&i.PixKeyType,
		&i.RecipientName,
		&i.RecipientDocument,
		&i.RecipientBank,
		&i.RecipientBranch,
		&i.RecipientAccount,
		&i.RecipientAccountType,
		&i.RecipientUserID,
		&i.ScheduledFor,
		&i.CompletedAt,
		&i.FailureReason,
		&i.AuthenticationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
