// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    kratos_identity_id,
    email,
    full_name,
    cpf
) VALUES ($1, $2, $3, $4)
RETURNING id, kratos_identity_id, email, full_name, cpf, balance_cents, daily_transfer_limit_cents, monthly_transfer_limit_cents, status, kyc_status, created_at, updated_at
`

type CreateUserParams struct {
	KratosIdentityID string         `json:"kratos_identity_id"`
	Email            string         `json:"email"`
	FullName         sql.NullString `json:"full_name"`
	Cpf              sql.NullString `json:"cpf"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.KratosIdentityID,
		arg.Email,
		arg.FullName,
		arg.Cpf,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.Email,
		&i.FullName,
		&i.Cpf,
		&i.BalanceCents,
		&i.DailyTransferLimitCents,
		&i.MonthlyTransferLimitCents,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, kratos_identity_id, email, full_name, cpf, balance_cents, daily_transfer_limit_cents, monthly_transfer_limit_cents, status, kyc_status, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.Email,
		&i.FullName,
		&i.Cpf,
		&i.BalanceCents,
		&i.DailyTransferLimitCents,
		&i.MonthlyTransferLimitCents,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, kratos_identity_id, email, full_name, cpf, balance_cents, daily_transfer_limit_cents, monthly_transfer_limit_cents, status, kyc_status, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.Email,
		&i.FullName,
		&i.Cpf,
		&i.BalanceCents,
		&i.DailyTransferLimitCents,
		&i.MonthlyTransferLimitCents,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByKratosID = `-- name: GetUserByKratosID :one
SELECT id, kratos_identity_id, email, full_name, cpf, balance_cents, daily_transfer_limit_cents, monthly_transfer_limit_cents, status, kyc_status, created_at, updated_at FROM users WHERE kratos_identity_id = $1 LIMIT 1
`

func (q *Queries) GetUserByKratosID(ctx context.Context, kratosIdentityID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByKratosID, kratosIdentityID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.Email,
		&i.FullName,
		&i.Cpf,
		&i.BalanceCents,
		&i.DailyTransferLimitCents,
		&i.MonthlyTransferLimitCents,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, kratos_identity_id, email, full_name, cpf, balance_cents, daily_transfer_limit_cents, monthly_transfer_limit_cents, status, kyc_status, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.Email,
		&i.FullName,
		&i.Cpf,
		&i.BalanceCents,
		&i.DailyTransferLimitCents,
		&i.MonthlyTransferLimitCents,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, kratos_identity_id, email, full_name, cpf, balance_cents, daily_transfer_limit_cents, monthly_transfer_limit_cents, status, kyc_status, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.KratosIdentityID,
			&i.Email,
			&i.FullName,
			&i.Cpf,
			&i.BalanceCents,
			&i.DailyTransferLimitCents,
			&i.MonthlyTransferLimitCents,
			&i.Status,
			&i.KycStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name = COALESCE($2, full_name),
    updated_at = NOW()
WHERE id = $1
RETURNING id, kratos_identity_id, email, full_name, cpf, balance_cents, daily_transfer_limit_cents, monthly_transfer_limit_cents, status, kyc_status, created_at, updated_at
`

type UpdateUserParams struct {
	ID       uuid.UUID      `json:"id"`
	FullName sql.NullString `json:"full_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.Email,
		&i.FullName,
		&i.Cpf,
		&i.BalanceCents,
		&i.DailyTransferLimitCents,
		&i.MonthlyTransferLimitCents,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserBalance = `-- name: UpdateUserBalance :exec
UPDATE users
SET balance_cents = balance_cents + $2
WHERE id = $1
`

type UpdateUserBalanceParams struct {
	ID           uuid.UUID     `json:"id"`
	BalanceCents sql.NullInt64 `json:"balance_cents"`
}

func (q *Queries) UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBalance, arg.ID, arg.BalanceCents)
	return err
}
